<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $report->title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
        }

        .header {
            text-align: center;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }

        .school-logo {
            width: 80px;
            height: 80px;
            margin: 0 auto 10px;
        }

        .report-title {
            font-size: 24px;
            font-weight: bold;
            margin: 10px 0;
        }

        .report-meta {
            font-size: 12px;
            color: #666;
        }

        .section {
            margin-bottom: 25px;
        }

        .section-title {
            font-size: 18px;
            font-weight: bold;
            color: #2563eb;
            border-bottom: 1px solid #e5e7eb;
            padding-bottom: 5px;
            margin-bottom: 15px;
        }

        .data-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        .data-table th,
        .data-table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        .data-table th {
            background-color: #f8f9fa;
            font-weight: bold;
        }

        .data-table tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        .summary-card {
            background-color: #f8f9fa;
            border: 1px solid #dee2e6;
            border-radius: 5px;
            padding: 15px;
            margin-bottom: 15px;
        }

        .summary-card h4 {
            margin: 0 0 10px 0;
            color: #495057;
        }

        .stats-grid {
            display: flex;
            justify-content: space-between;
            flex-wrap: wrap;
        }

        .stat-item {
            text-align: center;
            padding: 10px;
            margin: 5px;
            background-color: #ffffff;
            border-radius: 5px;
            border: 1px solid #dee2e6;
            min-width: 120px;
        }

        .stat-value {
            font-size: 24px;
            font-weight: bold;
            color: #2563eb;
        }

        .stat-label {
            font-size: 12px;
            color: #6c757d;
        }

        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #dee2e6;
            text-align: center;
            font-size: 10px;
            color: #6c757d;
        }

        .page-break {
            page-break-before: always;
        }
    </style>
</head>

<body>
    <div class="header">
        <div class="school-logo">
            <!-- School logo placeholder -->
            <div style="width: 80px; height: 80px; background-color: #e9ecef; border-radius: 50%; margin: 0 auto; display: flex; align-items: center; justify-content: center; font-size: 24px; color: #6c757d;">
                EDU
            </div>
        </div>
        <h1 class="report-title">{{ $report->title }}</h1>
        <div class="report-meta">
            <p>Generated on: {{ now()->format('F d, Y \a\t H:i') }}</p>
            @if($report->academic_year)
            <p>Academic Year: {{ $report->academic_year->name }}</p>
            @endif
            @if($report->school_class)
            <p>Class: {{ $report->school_class->name }}</p>
            @endif
            @if($report->date_from && $report->date_to)
            <p>Period: {{ $report->date_from->format('M d, Y') }} - {{ $report->date_to->format('M d, Y') }}</p>
            @endif
        </div>
    </div>

    @if($report->description)
    <div class="section">
        <h2 class="section-title">Report Description</h2>
        <p>{{ $report->description }}</p>
    </div>
    @endif

    @yield('content')

    <div class="footer">
        <p>Generated by EduVolt Pro Academic Management System</p>
        <p>Report ID: {{ $report->id }} | Generated by: {{ $report->creator->name ?? 'System' }}</p>
    </div>
</body>

</html>